project:
  type: book
  output-dir: _book

book:
  title: "合成菌群文献复现项目"
  author: "liuhaodong,luanyehui"
  chapters:
    - index.qmd
    - 01-community-timeseries.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand