# -----------------------------------------------------------------------
# Title: Assemble interaction coefficients
# Author: Ewa Merz (e2merz@ucsd.edu)
# Description: We use this script to assemble the interaction coefficients of all microbes that meet our performance criteria into a single data file.
# R version: R version 4.4.0 (2024-04-24) -- "Puppy Cup"
# -----------------------------------------------------------------------

## Required libraries
library(tidyverse) # awesome to reshape and wrangle data
library(data.table) # useful to read and write large files

## Read data
data <- read.csv("data/data_sequences_0.1_rel_ab_0.5_occ_binned_4_days_with_temperature.csv")

## Assemble model performance
# Retrieve the list of all performance summary files generated by the MDR S-map function.
files <- list.files("model_out/ASVs_Scripps_Pier_28092024/performance",recursive = T,full.names = T) # list all files in the performance folder

for (i in 1:length(files)){
  
  # Aggregate the performance metrics (Rho, RMSE) for each target ASV across its parameter grid.
  performance_i <- read.csv(files[i]) %>%
    mutate(count=1) %>%
    group_by(target) %>%
    summarise(rho_mean=mean(rho_fit), # average predictive skill
              rho_sd=sd(rho_fit), # average standard deviation in predictive skill
              rmse_mean=mean(rmse_fit), # average predictive error
              rmse_sd=sd(rmse_fit), # average standard deviation in predictive error
              const_pred_rho=mean(const_pred_rho), # predictive skill from persistence model
              const_pred_rmse=mean(const_pred_rmse), # predictive error from persistence model
              n_models=sum(count)) # number of models used
  
  if(i==1){performance <- performance_i}else{performance<-rbind(performance,performance_i)}
  
  print(i) # keep track of the function
  
}

# --- Quality Control Filtering ---
# We only retain interactions from models that demonstrated a baseline 
# level of predictive skill (Pearson's rho >= 0.2).
meet_performance_criteria <- performance %>%
  filter(rho_mean>=0.2) # keep models with a rho (Person's correlation between observations and predictions) larger than 0.2

# Create a whitelist of taxa that passed the performance threshold.
selected_taxa <- pull(meet_performance_criteria,"target")

## Interaction coefficients
# Iterate through only the "reliable" taxa to gather their ensemble-averaged coefficients.

for(i in 1:length(selected_taxa)) {
  
  target_i <- selected_taxa[i]
  
  # Load the weighted mean interaction coefficients for target_i.
  interactions_target_i <- read.csv(paste0("model_out/ASVs_Scripps_Pier_28092024/interactions/interaction_coefficients_target_",target_i,".csv")) %>% # read data
    separate(target_2,into=c("target_2","tp"),sep="_tp_") %>% # some variable name formatting
    separate(target_1,into=c("group_1"),sep="_",remove=F) %>%
    separate(target_2,into=c("group_2"),sep="_",remove=F) %>%
    
    # Apply secondary filtering. 
    # 1. target_2 must also be in the 'selected_taxa' list.
    # 2. Exclude non-specific taxonomic labels or environmental variables (temperature).
    filter(target_2%in%selected_taxa&!group_2%in%c("Div","Phylum","temperature")&!group_1%in%c("Div","Phylum","temperature")) %>% # remove ASVs without any taxonomic classification
    
    dplyr::rename(MDR_smap_coefficient=coefficient_w_mean) %>% # rename the MDR S-map coefficient
    select(-coefficient_w_sd,-tp) # remove standard deviation of the coefficient
  
  if(i==1){interactions <- interactions_target_i} else {interactions <- rbind(interactions,interactions_target_i)}
  
  print(i)  # keep track of the function
}

## Save interaction file
# Save the final assembled dataset using fwrite for high-performance writing of large CSVs.
fwrite(interactions,"model_out/MDR_smap_interactions_Scripps_Pier_ASVs_tp_2_28092024.csv")